feat: Add time to test result title
equinor/mad-project-hearing-test-client pull request #190
Opened 2023-04-17 11:37 UTC by ofredstie

The list of results now display date and time so that it is possible to differentiate between tests that were performed on the same day.

Closes #182

![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-17 at 13 31 57](https://user-images.githubusercontent.com/3359842/232473182-fdbc6dbf-08e1-46e9-a2b1-0f9e7c376f9b.png)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-04-17 at 13 32 01](https://user-images.githubusercontent.com/3359842/232473209-f6978589-b4b4-4ae5-b3a4-5e54c8685483.png)

2023-04-19 12:29 UTC, dansvend commented
Maybe you could have a chat with Vetle about displaying this in the best possible way? Since day of month and month could be confusing to people used to different orders of displaying these number. It could be displayed as `1. Jan 2023, 10:00` like one of the suggestions Vetle gave me. If displaying the the whole month `1. Januar 2023, 10:00` you need to make sure there's enough room for the text on small devices like iPhone SE.

2023-04-20 10:49 UTC, ofredstie commented
![Simulator Screenshot - iPhone 14 - 2023-04-20 at 08 41 22](https://user-images.githubusercontent.com/3359842/233344330-3fa8e422-3b93-4635-b4d4-11591e5559a0.png)

![Simulator Screenshot - iPhone 14 - 2023-04-20 at 08 41 43](https://user-images.githubusercontent.com/3359842/233344353-21104365-b886-4559-ab19-43a60377ae53.png)

2023-04-24 11:52 UTC, dansvend requested changes

2023-04-24 11:52 UTC, dansvend commented on components/common/molecules/TestResultItem.tsx
>              })}
This can be extracted into a util function to make sure that the date is displayed in the same way. Also if you change the format you only have to change it on place.

2023-05-03 09:03 UTC, dansvend requested changes

2023-05-03 09:03 UTC, dansvend commented on app.json
>      }
Please stage files in VS code one by one to make sure you don't commit things that should not be in the codebase. This should be removed.

2023-05-03 09:03 UTC, dansvend commented on navigation/utils.js
> +  };
I would put this directly into the `toLocaleDateString` function arguments instead of creating a new variable which might create TypeScript error due to the wrong type being specified for that options variable.

2023-05-03 11:28 UTC, dansvend approved these changes
Looks good 💪

2023-05-11 10:08 UTC, merged