feat: Add logo to splash screen
equinor/mad-project-hearing-test-client pull request #191
Opened 2023-04-19 08:41 UTC by ofredstie

Replaced default splash image with Hørselstest logo.

Closes #189

Matched backgroundColor to the background for splash.png and the background color for DefaultScreen (#F7F7F7).
Removed "resizeMode: contain" since this is the default  mode.

https://user-images.githubusercontent.com/3359842/233018378-b4817b8f-66db-40bc-8d18-932dd2e1735d.mov

2023-04-19 12:40 UTC, dansvend requested changes
I left a request to change something and added question ✍️

2023-04-19 12:40 UTC, dansvend commented on app.json
> +      }
This should be removed as it's automatically added when running `npm run build-simulator`.

2023-04-19 12:45 UTC, ofredstie commented on app.json
> +      }
That is a mistake, I will remove it ASAP

2023-04-19 13:04 UTC, ofredstie commented on app.json
> -      "resizeMode": "contain",
Good point, I'll ad it back in. Vetle is working on a new splash screen, pointed out some issues with the old one, so I won't request a new code review before that is in place. 😊

2023-04-19 13:40 UTC, dansvend approved these changes

2023-04-20 15:05 UTC, ofredstie commented
Found some issues with MAD splash screen in Figma, so @VetleW will provide updated graphical elements next week.

2023-04-20 15:09 UTC, ofredstie commented
Also noticed that the text "Hørselstest" in the logo is a bit blurry, most likely due to the small size (148x173 px). Suggested therefore to @VetleW that we should consider scaling up this logo. 

![Simulator Screenshot - iPhone 14 - 2023-04-20 at 17 06 35](https://user-images.githubusercontent.com/3359842/233409088-5493abc9-9010-441e-a809-d1743ad64c9f.png)

2023-04-26 11:03 UTC, ofredstie commented
https://user-images.githubusercontent.com/3359842/234556392-6403b5db-c26d-4645-9e80-67c8b062c57d.mov

2023-05-24 06:45 UTC, HaakonSvane submitted a review, later dismissed

2023-05-24 06:45 UTC, HaakonSvane commented on assets/images/splash.png
From Apple's documentation on launch screens:
(https://developer.apple.com/design/human-interface-guidelines/launching)

> __Avoid including text on your launch screen.__ Because the content in a launch screen doesn’t change, any text you display won’t be localized.

Would it be better to remove the app name and just use the icon for this screen instead? In the case where you wanted to change the name of the app or add localization to it, you don't have to update your splash screen every time as well that way.

2023-05-24 06:45 UTC, HaakonSvane commented on assets/images/splash.png
I noticed that the white area around the top portion of the image looks cropped in the demo video you provided. A solution to this is to make the image as wide as the largest possible device, then use `"resizeMode": "cover"` (assuming it centeres the image automatically in this mode)

2023-05-24 08:37 UTC, ofredstie commented on assets/images/splash.png
@VetleW I think Haakon has a valid point here, what do you think?

2023-05-24 08:38 UTC, ofredstie commented on assets/images/splash.png
@VetleW What do you think, should we try it out, think it might look nicer that way

2023-05-24 12:38 UTC, VetleW commented on assets/images/splash.png
It is a very valid point. But I think it's a bigger job than just changing this one screen. We have many others designed in the same way [here](https://www.figma.com/file/0Y6LDJW2LWLdHlVOF2Lg1DR2/Splash-Screens?type=design&node-id=2037-10654&t=LCxmsHcON4fVpclj-4) so all the designers should probably be involved.

2023-05-24 12:39 UTC, VetleW commented on assets/images/splash.png
Definitely worth a try

2023-05-25 12:05 UTC, ofredstie commented on assets/images/splash.png
You fix a larger splash screen when you have time @VetleW ?

2023-06-07 07:37 UTC, HaakonSvane approved these changes
Looks nice 👌👌

2023-06-07 08:01 UTC, merged