fix: Disable "Se resultat" button during loading of result
equinor/mad-project-hearing-test-client pull request #197
Opened 2023-05-10 12:04 UTC by ofredstie

During loading of the result after a completed test the "Se resultat" button will be disabled and renamed to "Analyserer...".

Closes #196

2023-05-11 13:33 UTC, dansvend requested changes
I left some comments on possible changes but you could also ask Adrian to get his opinions as well :)

2023-05-11 13:33 UTC, dansvend commented on components/common/EDS/Button.tsx
> +  const getTextColor = () => {
Customization of common components like Button, Input etc. should avoided in project code and should be done in a component library like mad-expo-core instead to avoid people doing the same work multiple times.

2023-05-14 20:23 UTC, ofredstie commented on components/common/EDS/Button.tsx
> +  const getTextColor = () => {
I agree, will change it back to the way it was. 
Looked at the expo core button and it seems that it does not support outline style yet, will bring it up at tomorrows dev meeting. Think it could a good task for me to implement this in the expo core to familiarize myself with this repo.

2023-05-23 05:45 UTC, dansvend requested changes

2023-05-23 05:45 UTC, dansvend commented on components/common/molecules/TestResultItem.tsx
> +    if (data.level) setChartData(getChartData(data.level));
The component is defined to always have a `data` object of `TestResult` type so this can be removed.

2023-05-23 07:16 UTC, ofredstie commented on components/common/molecules/TestResultItem.tsx
> +    if (data.level) setChartData(getChartData(data.level));
Fixed

2023-05-24 07:22 UTC, HaakonSvane requested changes

2023-05-24 07:22 UTC, HaakonSvane commented on package.json
> +    "react-native": "0.70.8",
What caused this upgrade?
I see that the expo version is still the same and that the pipeline is failing. Might be related.

Try running fresh install locally and push any lockfile changes. Here is the fresh install script (from OM Inspection)
![Screenshot 2023-05-24 at 08 52 52](https://github.com/equinor/mad-project-hearing-test-client/assets/36899138/d6543336-027b-43db-8ea2-7378bd0921d3)

2023-05-25 11:07 UTC, HaakonSvane approved these changes
Looks nice 👍

2023-06-02 09:19 UTC, dansvend approved these changes

2023-06-05 13:23 UTC, merged